version: '3.8'
services:
  db:
    image: postgres
    environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=chain-vote-db
    ports:
        - "5432:5432"
  api:
    image: chain-vote-api
    environment:
      - GIN_MODE=release
    ports:
      - "8080:8080"
    depends_on:
        db:
          condition: service_started
    restart: unless-stopped