version: '3.8'
services:
  db:
    image: postgres
    environment:
        - POSTGRES_USER=chain-vote
        - POSTGRES_PASSWORD=chain-vote
        - POSTGRES_DB=chain-vote-db
    ports:
        - "5432:5432"
  api:
    image: chain-vote-api
    environment:
      - GIN_MODE=release
      - DATABASE_URL="postgresql://chain-vote:chain-vote@localhost:5432/chain-vote-db"
      - PORT="8080"
    ports:
      - "8080:8080"
    depends_on:
        db:
          condition: service_started
    restart: unless-stopped